const express = require('express')
const MainController = require('../controllers/mainController')
const router = express.Router()

router.get('/',MainController.getMain)
router.get('/buocxa',MainController.getBuocxa)
router.get('/sanluong',MainController.getSanluong)
router.get('/tinhtoan',MainController.getTinhtoan)
router.get('/createTT',MainController.getAddTT)
router.get('/createSL',MainController.getAddSL)
router.post('/tinhtoan/create',MainController.postCreateTT)
router.post('/hochua/create',MainController.postCreateHC)
router.post('/buocxa/create',MainController.postCreateBX)
router.get('/sanluong/edit/:id',MainController.getEditSL)
router.post('/sanluong/update/electric/:id',MainController.postUpdateESL)
router.post('/sanluong/update/revenue/:id',MainController.postUpdateRSL)
router.get('/tinhtoan/edit/:id',MainController.getEditTT)
router.post('/tinhtoan/update/:id',MainController.postUpdateTT)
router.get('/tinhtoan/delete/:id',MainController.getDeleteTT)
router.get('/getFile',MainController.getFile)
router.post('/click',MainController.getClick)
router.get('/exportSL',MainController.getExportAllSL)
router.get('/exportTT',MainController.getExportAllTT)
router.post('/download',MainController.getDownloadSL)
router.get('/fetch',MainController.getFetchData)

module.exports = router